spring.application.name=riegos_garcia

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=riego.jardines.garcia@gmail.com
spring.mail.password=vxrswkiatktwtcaq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

correo.destino=riego.jardines.garcia@gmail.com